import 'reflect-metadata';
import {Container} from 'inversify';
import {ILogger} from './Logger/ILogger.js';
import {TYPES} from './types.js';
import {PinoLogger} from './Logger/PinoLogger.js';
import {Application} from '../Application.js';
import {IConfig} from './Config/IConfig.js';
import {Config} from './Config/Config.js';
import {DatabaseClient} from './Database/database-client.interface.js';
import {MongoDatabaseClient} from './Database/mongo-database-client.js';
import {IUserService} from './DAL/userService.js';
import {UserService} from './DAL/userService.js';
import {RentalOfferService} from './DAL/rentalOfferService.js';
import {AuthController} from '../controllers/AuthController.js';
import {CommentRepository} from './DAL/comment.repository.js';
import {CommentController} from '../controllers/CommentController.js';
import {OfferController} from '../controllers/OfferController.js';
import {UserController} from '../controllers/UserController.js';
import {IAuthService} from './IAuthService.js';
import {AppExceptionFilter, ExceptionFilter} from './app-exeption-filter.js';

export const container = new Container();
container.bind<ILogger>(TYPES.Logger).to(PinoLogger).inSingletonScope();
container.bind<Application>(TYPES.Application).to(Application).inSingletonScope();
container.bind<IConfig>(TYPES.Config).to(Config).inSingletonScope();
container.bind<DatabaseClient>(TYPES.DatabaseClient).to(MongoDatabaseClient).inSingletonScope();
container.bind<IUserService>(TYPES.UserService).to(UserService).inSingletonScope();
container.bind<RentalOfferService>(TYPES.RentalOfferService).to(RentalOfferService).inSingletonScope();
container.bind<CommentRepository>(TYPES.CommentRepository).to(CommentRepository).inSingletonScope();
container.bind<AuthController>(TYPES.AuthController).to(AuthController).inSingletonScope();
container.bind<CommentController>(TYPES.CommentController).to(CommentController).inSingletonScope();
container.bind<OfferController>(TYPES.OfferController).to(OfferController).inSingletonScope();
container.bind<UserController>(TYPES.OfferController).to(UserController).inSingletonScope();
container.bind<IAuthService>(TYPES.AuthService).to().inSingletonScope();
container.bind<ExceptionFilter>(TYPES.ExceptionFilter).to(AppExceptionFilter).inSingletonScope();
